"use strict";
exports.__esModule = true;
var mobile_1 = require("./mobile");
var mobile1 = new mobile_1.Mobile("Nokia", 3210, "China", 16, "Black", true, 4, 200);
var mobile2 = new mobile_1.Mobile("iPhone", 3, "California", 32, "White", false, 1, 600);
var mobile3 = new mobile_1.Mobile("Samsung Galaxy", 10, "Corea", 64, "Grey", true, 2, 900);
var mobiles = [];
mobiles.push(mobile1);
mobiles.push(mobile2);
mobiles.push(mobile3);
// console.log(mobiles);
console.log(mobile1.name);
console.log(mobile1.model);
console.log(mobile1.trademark);
console.log(mobile1.sdSize);
console.log(mobile1.color);
console.log(mobile1.is5G);
console.log(mobile1.cameraNumber);
console.log(mobile1.price);
